### PR TITLE
🤖 intitalised

### PR DESCRIPTION
**Pull request by RGHANILOO**
bot is initialised. 
i am still having issue with `npm run lint`

### CODE REVIEW

**Comment by sulphite** [comment]
my console says we need an eslint config file. I tried using the prompts to make the standard one but it didn't work and needed tweaks..... you want to add it or should I?

**Comment by RGHANILOO** [comment]
Hey @sulphite 

sorry only just saw your message,GH failed to notify me 
i have got a `.eslintrc.json`in the root of project on my end. although rules within are  not filled in

```js
{
	"extends": "eslint:recommended",
	"env": {
		"node": true,
		"es6": true
	},
	"parserOptions": {
		"ecmaVersion": 2021,
        "sourceType": "module"
	},
	"rules": {
        

	}
}
```

**Comment by sulphite** [comment]
@RGHANILOO oh cool, can you put it in this PR? We will need to add some typescript stuff in there as well to make it work, google shows a plethora of different ways to do it but this looks simple and barebones: https://learntypescript.dev/12/l3-eslint

**Comment by RGHANILOO** [comment]
@sulphite  Hey i have set up the eslint removed the .eslintrc and set it in the root.
i haven't worked in TS structure before unsure what rules to add. at this stage

**Review by sulphite — APPROVED** [review]
looks good, all seems to work on my end

**Pull request merged**
